#Add all the vhdl files needed for your design
 read_vhdl -library work ../rtl/user_design/EXTERNAL_FILE.vhd
 read_vhdl -library work ../rtl/user_design/AND_GATE.vhd
 read_vhdl -library work ../rtl/user_design/AND_GATE_3IN.vhd
 read_vhdl -library work ../rtl/user_design/AND_GATE_4IN.vhd
 read_vhdl -library work ../rtl/user_design/AND_PLANE.vhd
 read_vhdl -library work ../rtl/user_design/OR_GATE.vhd
 read_vhdl -library work ../rtl/user_design/OR_GATE_4IN.vhd
 read_vhdl -library work ../rtl/user_design/NOT_GATE.vhd
 read_vhdl -library work ../rtl/user_design/XOR_GATE.vhd
 read_vhdl -library work ../rtl/user_design/REG.vhd
 read_vhdl -library work ../rtl/user_design/MUX_2X1.vhd
 read_vhdl -library work ../rtl/user_design/MUX_4X1.vhd
 read_vhdl -library work ../rtl/user_design/MUX_8X1.vhd
 read_vhdl -library work ../rtl/user_design/MUX_16X1.vhd
 read_vhdl -library work ../rtl/user_design/DECODER.vhd
 read_vhdl -library work ../rtl/user_design/ENCODER.vhd
 read_vhdl -library work ../rtl/user_design/FULL_ADDER.vhd
 read_vhdl -library work ../rtl/user_design/ADDER.vhd
 read_vhdl -library work ../rtl/user_design/COUNTER_6bit.vhd
 read_vhdl -library work ../rtl/user_design/MULTIPLIER.vhd
 read_vhdl -library work ../rtl/user_design/LOGIC_OPERATORS.vhd
 read_vhdl -library work ../rtl/user_design/SHIFTER.vhd
 read_vhdl -library work ../rtl/user_design/EQUIVALENCE_OPERATOR.vhd
 read_vhdl -library work ../rtl/user_design/REQUEST_MANAGER.vhd
 read_vhdl -library work ../rtl/user_design/STATUS_PLA.vhd	
 read_vhdl -library work ../rtl/user_design/INSTR_MEMORY.vhd
 read_vhdl -library work ../rtl/user_design/CONTROL_UNIT.vhd
 read_vhdl -library work ../rtl/user_design/DATA_MEMORY.vhd
 read_vhdl -library work ../rtl/user_design/INPUT_STAGE.vhd
 read_vhdl -library work ../rtl/user_design/OUTPUT_STAGE.vhd
 read_vhdl -library work ../rtl/user_design/BRICK.vhd
 read_vhdl -library work ../rtl/user_design/LOGIC_UCODE.vhd
 read_vhdl -library work ../rtl/user_design/LOGIC_UNIT.vhd
 read_vhdl -library work ../rtl/user_design/LOGIC_ELEMENT.vhd
 read_vhdl -library work ../rtl/user_design/BOTTOM_LAYER.vhd
 read_vhdl -library work ../rtl/user_design/ROUTING_ELEMENT.vhd
 read_vhdl -library work ../rtl/user_design/UPPER_LAYER.vhd
 read_vhdl -library work ../rtl/user_design/PYRAMID.vhd
